### ISSUE TITLE
errors that are thrown by pipeline to debug

### ISSUE THREAD

**Issue by ebridge2** [NeuroDataDesign/fngs#14]

**Comment by ebridge2** [comment]
Warning: BBR self registration failed.
Traceback (most recent call last):
  File "/usr/local/bin/ndmg_func_pipeline", line 11, in <module>
    load_entry_point('ndmg==0.0.49', 'console_scripts', 'ndmg_func_pipeline')()
  File "build/bdist.linux-x86_64/egg/ndmg/scripts/ndmg_func_pipeline.py", line 227, in main
  File "build/bdist.linux-x86_64/egg/ndmg/scripts/ndmg_func_pipeline.py", line 142, in ndmg_func_pipeline
  File "build/bdist.linux-x86_64/egg/ndmg/register/register.py", line 508, in register
  File "build/bdist.linux-x86_64/egg/ndmg/register/register.py", line 426, in self_align
  File "build/bdist.linux-x86_64/egg/ndmg/register/register.py", line 209, in resample
  File "/usr/local/lib/python2.7/dist-packages/nilearn/image/resampling.py", line 398, in resample_img
    img = _utils.copy_img(img)
  File "/usr/local/lib/python2.7/dist-packages/nilearn/_utils/niimg.py", line 131, in copy_img
    return new_img_like(img, _safe_get_data(img).copy(), get_affine(img).copy(),
  File "/usr/local/lib/python2.7/dist-packages/nilearn/_utils/niimg.py", line 28, in _safe_get_data
    return img.get_data()
  File "/usr/local/lib/python2.7/dist-packages/nibabel/spatialimages.py", line 572, in get_data
    data = np.asanyarray(self._dataobj)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 583, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/usr/local/lib/python2.7/dist-packages/nibabel/arrayproxy.py", line 145, in __array__
    raw_data = self.get_unscaled()
  File "/usr/local/lib/python2.7/dist-packages/nibabel/arrayproxy.py", line 140, in get_unscaled
    mmap=self._mmap)
  File "/usr/local/lib/python2.7/dist-packages/nibabel/volumeutils.py", line 524, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "/usr/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 312, in _read
    uncompress = self.decompress.decompress(buf)
zlib.error: Error -3 while decompressing: invalid distance code

kara sub 24-6
